### ISSUE TITLE
img2url package level issue

### ISSUE THREAD

**Issue by FatBobGo** [huntzhan/img2url#8]
新年好。我在尝试使用IDE运行 img2url 代码。因为包的引用问题发生错误。请问一下应该怎样放置代码才能正确运行？

**Comment by huntzhan** [comment]
我没有试过在 IDE 里开发。如果是缺少依赖的问题，请先运行
https://github.com/huntzhan/img2url/blob/d339bb2bf0ecf0a119cd62a2672630d89ed403d0/.travis.yml#L9-L10

我已经不再维护这个 repo 了，谢谢
